### ISSUE TITLE
Failed to download source "Libpng"

### ISSUE THREAD

**Issue by oliverhowells** [minimaxir/video-to-gif-osx#3]
I'm new to using the terminal but I gave it a shot anyway. Home-brew installed fine, the next step looked like it almost worked but at the end I got an error. This is what showed up. I hope this is more help than trouble.

Olivers-MacBook-Air:~ oliverhowells$ brew install ImageMagick mplayer gifsicle
==> Installing dependencies for imagemagick: xz, libtool, jpeg, libpng, f
==> Installing imagemagick dependency: xz
==> Downloading http://fossies.org/linux/misc/xz-5.0.6.tar.gz

curl: (22) The requested URL returned error: 410 Gone
Trying a mirror...
==> Downloading http://tukaani.org/xz/xz-5.0.6.tar.gz
###### ################################################################## 100.0%

==> ./configure --prefix=/usr/local/Cellar/xz/5.0.6
==> make install
🍺  /usr/local/Cellar/xz/5.0.6: 58 files, 1.5M, built in 70 seconds
==> Installing imagemagick dependency: libtool
==> Downloading http://ftpmirror.gnu.org/libtool/libtool-2.4.2.tar.gz
###### ################################################################## 100.0%

==> Patching
patching file libltdl/config/ltmain.sh
==> ./configure --prefix=/usr/local/Cellar/libtool/2.4.2 --program-prefix=g --en
==> make install
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Summary
🍺  /usr/local/Cellar/libtool/2.4.2: 69 files, 2.5M, built in 40 seconds
==> Installing imagemagick dependency: jpeg
==> Downloading http://www.ijg.org/files/jpegsrc.v8d.tar.gz
###### ################################################################## 100.0%

==> ./configure --prefix=/usr/local/Cellar/jpeg/8d
==> make install
🍺  /usr/local/Cellar/jpeg/8d: 18 files, 772K, built in 32 seconds
==> Installing imagemagick dependency: libpng
==> Downloading https://downloads.sf.net/project/libpng/libpng16/1.6.13/libpng-1

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "libpng"
Download failed: https://downloads.sf.net/project/libpng/libpng16/1.6.13/libpng-1.6.13.tar.xz

**Comment by minimaxir** [comment]
That's an issue with Homebrew unfortunately. Sounds like a connection error and it might not hurt to try again.
